- name: create backend directory
  file:
    path: ~/code
    state: directory

- name: extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/code

- name: install dependencies
  command: npm install
  args:
    chdir: ~/code

- name: start server
  command: pm2 start npm -- start
  #command: node main.js
  args:
    chdir: ~/code/dist
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"